export const WEBSOCKET_CONNECTED = 'WEBSOCKET_CONNECTED';
export const WEBSOCKET_DISCONNECTED = 'WEBSOCKET_DISCONNECTED';
export const WEBSOCKET_DATA_RECEIVED = 'WEBSOCKET_DATA_RECEIVED';
export const UPDATE_CANDLES = 'UPDATE_CANDLES';
